CREATE SEQUENCE PROFILE_SEQ; 
CREATE SEQUENCE PRACTIC_SEQ; 
CREATE SEQUENCE LANGUAGE_SEQ; 
CREATE SEQUENCE HOBBY_SEQ; 
CREATE SEQUENCE EDUCATION_SEQ;
CREATE SEQUENCE SKILL_SEQ;
CREATE SEQUENCE CERTIFICATE_SEQ;
CREATE SEQUENCE COURSE_SEQ;